### ISSUE TITLE
Request: Arch-based distribution support

### ISSUE THREAD

**Issue by tedtms** [lucent-sea/Remotely#129]
Hello!

I've been using Remotely for quite some time now and absolutely love it. However, I have some Arch-based systems (Manjaro, specifically) that I'm trying (and failing so far) to get Remotely Client working on.

So far, I've been able to install the packages normally installed by the client installation script, including dotnet-runtime, and my client system appears in my remote control server menu with its system statistics, etc. However, attempting to remote control immediately results in a "Failed to start remote control" message. I am, interestingly enough, able to execute bash commands on the client system using the Remotely console.

I realize that you've already said Ubuntu is the only tested client distribution, but if you have the time or interest in making an Arch-based system work, I'd be forever grateful!

Cheers,
Ted

**Comment by lucent-sea** [comment]
I was willing to look at it this morning, but Manjaro won't boot on Hyper-V.  I might troubleshoot later.

**Comment by tedtms** [comment]
Any luck with the VM?

**Comment by lucent-sea** [comment]
Sorry, man.  I haven't had the chance yet.  All my allotted "Remotely time" has been spent answering emails.

If you want to help me out, that'd be awesome.  On Windows 10 Pro, try to get Manjaro working on Hyper-V.  And give me the TLDR on how to replicate it.  :)  Also, which flavor of Manjaro?  I tried manjaro-xfce-20.1-200911-linux58.

**Comment by CJ1169** [comment]
Theoretically any flavour will work of Manjaro. They all have identical repos. KDE and XFCE are both _very_ popular.

I don't use Hyper-V, I use VirtualBox and libvirt/qemu/kvm - but my work PC has Hyper-V and I may be able to squeeze that test in eventually.

If you ever do support Arch-based, a PKGBUILD is the recommended way to go and it could either be on the AUR or just hosted here.

**Comment by CJ1169** [comment]
Booted first try for me:
Make sure you have Secure Boot in Hyper-V's options disabled

After booting, the GUI did not load because you'll need [xf86-video-fbdev](https://wiki.archlinux.org/index.php/Hyper-V#Xorg) installed (the video driver for hyper-v). Either you can install it, or just use `sudo manjaro-architect` for the CLI installer.

Either way, use Alt+Ctrl+F2 to get into the 2nd TTY. Login as manjaro w/ password manjaro

Get the drivers going or go through the CLI installer. I personally use the CLI installer 9/10 times anyway.

If requested, I'm more than happy to remote control to install it for you or simply zip up a hyper-v machine to send.

**Comment by lucent-sea** [comment]
Added a separate install script for it.  I noticed some UI weirdness with some elements (like the session indicator window), but it seems to be working.

**Comment by CJ1169** [comment]
Can confirm that Arch-based support works. No graphical noises/bugs here on bare-metal.

Couple suggestions: 
For the install script I would use `pacman -Syu dotnet-runtime-3.1 libx11 unzip glibc libgdiplus xclip jq curl --noconfirm` This is to make sure people do not accidentally break their systems.

Dual monitor support acts a little funky - specifically that there is a 'Monitor 0' for both screens simultaneously instead of 'Monitor 0' + 'Monitor 1'.

Looking good! Thank you
