### ISSUE TITLE
Is there a way of deleting a duplicated computer from the listing 

### ISSUE THREAD

**Issue by rhinopctec** [lucent-sea/Remotely#139]
Is there a way of deleting a duplicated computer from the listing

**Comment by swilkey** [comment]
Yes. Take a look in the tickets that Jared has already closed - you'll find
the answer there. Sorry I can access the internet from here, just email, so
I can't give you the link.

**Comment by swilkey** [comment]
Well I can't find that ticket, but I know he gave me the answer to that question back in March or April.  Anyway, I'm now at a computer with internet access and so I'm passing on what he taught me.

You can select the computers you want to delete graphically on the grid or you can switch to the console mode and select them.  After you've selected them, switch to console mode and use the "remove" command to delete the selected machines from the grid.  Note that you can get help listing all the commands by typing "help" without the quotes.

Also note that I've seen some situations where the database has got corrupted and you cannot delete computers from the grid. At this point all you can do is to create a fresh database (I keep a copy of the last one I have from a fresh install so that I can restore it) and then reinstall all your clients to connect to it.  Fortunately I've only experienced this twice, after I was doing a lot of experimenting so I don't think it would happen normally to people.

**Comment by lucent-sea** [comment]
Yes, the "remove" command.

**Comment by rhinopctec** [comment]
your the best
