### ISSUE TITLE
Optional (via command line) allow to connect without user consent

### ISSUE THREAD

**Issue by hubermarkus** [lucent-sea/Remotely#147]
When the instant support (or even the service) is started with a special command line arg (e.g. /nouserprompneeded) then the supporter should be able to connect without user consent.

**Comment by lucent-sea** [comment]
There's already an unattended mode for this.  It needs to be initiated through the Agent in order for everything to work properly, though.

**Comment by sven-weber** [comment]
I would also be interested in the feature. Mainly to apply the following workflow: 

I don't want to access client PCs completely unattended but rather unattended as soon as the clients provides a session id (similar to the workflow in e.g. Teamviewer).
This way, when I get a support request the client can send the session ID, leave his PC and I can connect as soon as I have time to handle the request. Without this possibility, the client would have to wait till I'm connected in order to allow the remote session.

This sure only applied to support request where the clients does not need to present (which is most of the support requests in my case).

So in my point of view this differs from the current possibilities to have a completely unattended access. 

If you want to integrate this I'm happy to provide a PR with the needed changes. 

P.S. loving your work and the project. This is the coolest thing I have seen for a long time!

**Comment by lucent-sea** [comment]
This workflow will be possible after the following feature is implemented:  https://github.com/lucent-sea/Remotely/issues/152
