### ISSUE TITLE
Hard Coded Organization ID

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#158]
Good Day,
To All,

Requesting for your kind assistance.
For Remotely Agent installer if there is way to input the Organization ID before I build new exe to already hard coded to the .exe like server url.

Thank You

**Comment by Nil0x** [comment]
Hello,

I had a hard time understanding your question, but I'll give it a shot. This answer is regarding the Windows Installer since the Linux installer scripts have the Hostname/Organization fields already specified in the script ( this is probably generated during the setup ). 

When you download a Resident Agent under Downloads -> Resident Agent -> Windows Installer , the way it autofills the organization id is by detecting the organization id your user currently belongs to and then populating it within the installer name . The installer then extracts it from the name when you run it, and autofills the organization id field. As far as I know, there's no way to include the server url automatically possibly due to problems with including certain characters within windows filenames and/or polluting the installer name.

The way I got around this was by using NSIS ( https://nsis.sourceforge.io/Main_Page ). I created my own custom installer then I wrapped the Remotely Installer within it, and then called it with the command arguments I wanted ( like my server url/org id/quiet mode based off whatever xyz user condition I specified ) within the NSI config file that is needed to generate one. The output is your own installer with whatever dialogues you specify within the NSI file - that calls the remotely installer silently.

There's an example of calling the installer on the Downloads page, but here: 
Remotely_Installer.exe -install -quiet -organizationid "0b3d706b-9c5d-41e6-8ae9-5720d16324e6" -serverurl "https://remotely.mytechshop.com"

I'll be honest, it's a bit of hack that is masked quite well. I'm not sure if .NET core has the ability to create an on-demand installer with custom settings. but  I guess you could submit a feature request to see if it's possible?

Thanks.

**Comment by stevesobol** [comment]
It may not be necessary to use .NET. I use Inno Setup to create my installers.

**Comment by sinichi19** [comment]
thank you sir @Nil0x i will try, thank you for your kind assistance.

**Comment by lucent-sea** [comment]
It would be possible to build the installers and GUI clients on-demand with all the info hard-coded.  However, the Windows apps can only be built on Windows due to the use of .NET Framework and WPF, and most people are running Remotely on Linux.  So I'd need to set up a Windows server with enough resources to handle all requests and offer it as a free service, which isn't feasible.

This has been one of the more challenging parts of the project, making everything work without requiring a recompile and without being too inconvenient to supply the info at runtime.

The Windows build requirement may change in the future.  The .NET Framework wrappers were only used because too many people were unhappy about the file size of self-contained .NET Core apps.  .NET 5 is releasing next month, and it has better trimming capability to reduce the output size.  If it can make the self-contained apps small enough to make everyone happy, I can drop the .NET Framework wrappers and use AvaloniaUI instead of WPF for the Windows clients.

That should pave the way for the Remotely server itself to be able to compile the apps.  Then it's just a matter of finding time to do the work.

(As a side note, another tactic I tried was appending a block of empty bytes at the end of the executable at download-time and filling it with the info.  It works, but it breaks the digital signature.  I found a few articles about how to insert the bytes in another section of the PE without breaking the signature, but I couldn't get it to work.  It may have been patched.)
