### ISSUE TITLE
Remote Control Requires Authentication seems not to work

### ISSUE THREAD

**Issue by Scaff31** [lucent-sea/Remotely#159]
Hello,

Thanks for the great job on Remotely this app is awesome.

I'm trying to figure out how to make remote connections start on the login page and not on the active user's session. Whether or not I enable the "Remote Control Requires Authentication" option, I always take control of the active session and not the authentication page.

If someone has an idea I'll take it.

Scaff

**Comment by swilkey** [comment]
Scaff,

While I didn't write remotely and therefore cannot speak authoritatively 
about it, my understanding of how Windows works is that if you are using 
the instant support client you can only work within the current users' 
session as that is where you are running the app from.  If you are using 
the remotely service you would be able to logon, but windows computers 
are different from servers and so they are not designed to run a 
separate session for someone remotely accessing them versus someone 
physically at them.  Additionally, since the purpose of remotely is for 
support, you want to be able to experience the environment of the user 
you are trying to support.  Therefore the only way to start at the login 
screen of Windows is for the user to lock their computer when they are 
not using it and you to control it during that time.

If you are wanting to use remotely for support just in terms of 
installing something or checking for problems by accessing the registry 
or the file system, you might want to consider the command line access 
or the powershell access available from the console of remotely - this 
allows you to run things that don't interact with the user session.

I hope that helps
Stephen

------ Original Message ------

**Comment by Scaff31** [comment]
I use the agent installed on a machine and not instant support. I'm trying to find out if it is possible to open the remote desktop on the default authentication page and not on the active session. Indeed I want to use it for Windows server support but also on classic workstations.

In the case of workstations, the instant support works perfectly.

I'm mainly looking to secure access to the servers that I should take control of remotely. By forcing authentication for each remote takeover.

Thanks for your answer stephen

**Comment by Nil0x** [comment]
@Scaff31 ,

Are you asking in a terminal server ( or just a workstation with someone RDP'd onto it ) setup - you'd like all new remote connection attempts to start on the console rather than the active session? If so, then the RemoteControlRequiresAuthentication doesn't do that , that's for internal use to only limit access to the remote control page and web socket endpoint for users that are authenticated ( refer to this issue: https://github.com/lucent-sea/Remotely/issues/40 ). It's set to true by default. 

Can you explain your question a bit more clearly? I'm not sure if you're referring to a TS/RDP type issue, or if you're asking if a remote control initiator needs to log in through windows before accessing a session ( or internally through remotely ).

Thanks.

**Comment by Scaff31** [comment]
That's right,

I rephrase my question. When connecting to an RDS server, I want remotely to open on the default console and not on the active RDS session.

Thanks for the answer Nil0x

**Comment by Nil0x** [comment]
That makes much more sense and you're correct about this ( It happens to me as well ). Unfortunately, the default/hard coded behavior seems to be that it auto selects the active RDP session ( or maybe it's just random? ) instead of the console. Just off the top of my head you could call and set it to 0 ( which is the console ) as a hacky way to get around it:

https://github.com/lucent-sea/Remotely/blob/d1b82d08ff21fedd6815d272419ffd8f9d5bc7b1/Server/wwwroot/src/RemoteControl/ViewerHubConnection.ts#L53

I'll need some time to track down where the *real* condition is that determines which session it selects. You can create a feature request to see if someone else can push a PR to fix this or add a config value which turns it off.

**Comment by lucent-sea** [comment]
Actually, this was just something I missed in AppLauncherWin.cs.  `LaunchRemoteControl` was supposed to be the same as `RestartScreenCaster`, where:

`forceConsoleSession: Shlwapi.IsOS(OsType.OS_ANYSERVER) && targetSessionId == -1,`

So the behavior is, if it's Windows Server and no session ID is specified, it defaults to the console.  For consumer versions of Windows, where only 1 session ID can be active, it will first look for an active RDP session.  If there isn't one, it goes to the console.

Once you're connected, you can switch sessions in the sidebar.

**Comment by lucent-sea** [comment]
And of course, I'll include this in the next release.  :D

**Comment by Scaff31** [comment]
Thank for RDS server now it's working.

Just another question my remotely was debian server and locales are configure on "French keyboard with accent", But when i remote numpad not work correctly if i press "1" it's "&" and "Alt GR" key was not binding

**Comment by lucent-sea** [comment]
Unfortunately, localization isn't something I can work on right now.
