### ISSUE TITLE
There was an unhandled exception again.

### ISSUE THREAD

**Issue by wikimao** [lucent-sea/Remotely#177]
There was an unhandled exception, windows 10 64bit latest.

![image](https://user-images.githubusercontent.com/8460045/100185474-e7d5b980-2f1e-11eb-88e5-42a3814ded88.png)
[Remotely_Logs.log](https://github.com/lucent-sea/Remotely/files/5594529/Remotely_Logs.log)

**Comment by lucent-sea** [comment]
The stack trace shows the same thing.  It has nothing to do with Remotely code.  Publish the app without the Trim option.  It's broken at the moment, as it's still in preview state.  The .NET team says it should be fully working in .NET 6.

If you're using the .NET Framework wrapper, make sure "Remotely_Desktop.exe" process is killed, or else it won't be able to extract the latest version into the temp directory.  You can be sure it's opening the latest version by deleting the "%temp%\Remotely_Desktop\" folder.

Or you can not use the wrapper.  The EXE size is larger, though, because it's not compressed.  There's a GitHub issue open with the .NET team to add compression to single-file publishing.  If it gets added, then the wrapper will be unnecessary.

**Comment by wikimao** [comment]
perfect. Working now. 
- removed from Temp and kill the task running files.
