### ISSUE TITLE
Linux Desktop app won't launch

### ISSUE THREAD

**Issue by regs01** [lucent-sea/Remotely#178]
Trying to launch Remotely_Desktop elf, but it fails on some dependency
Error:
  An assembly specified in the application dependencies manifest (Remotely_Desktop.deps.json) was not found:
    package: 'Avalonia.Skia.Linux.Natives', version: '1.68.0.2'
    path: 'runtimes/linux-x64/native/libSkiaSharp.so'

It's Ubuntu 20.10

**Comment by lucent-sea** [comment]
This is due to the PublishTrimmed feature no longer working.  I forgot to remove it from the Linux project when I removed it from the Windows projects.

I just removed them on Master branch.

**Comment by regs01** [comment]
Well, tried the latest version. Still asking for same assembly.

**Comment by lucent-sea** [comment]
It looks like they also changed the single-file publishing behavior in .NET 5.  https://github.com/dotnet/core/issues/5409

`IncludeAllContentForSelfExtract=true` is now also required.

I don't know if I'll do another release, though.  I'm thinking of archiving the project.  I'm kind of tired of doing free work for people.

**Comment by stevesobol** [comment]
Now hold on. You've said similar stuff in the past, but then when I suggest that I can work on it, you don't want me to, BUT you suggest that I can fork and open pull requests.

I'm doing some customizations for myself. Some of them would be helpful to the general public, like SSO capability if you don't have that baked in already. Or macOS support.

I mean seriously. I love Remotely, If I was at a point where I was making money with it - and given the situation with COVID, I would definitely like to publicize my 25 years of tech support experience and focus on remote support - if I was making money with it, you WOULD be getting some of that money. I can guarantee it.

You're driving me insane, sir. Please make up your mind, because this would be the second time you've flip-flopped in about two months. :)

**Comment by lucent-sea** [comment]
This project started years ago as InstaTech.  I've put thousands of hours of work into it to get to where it is today.

At first, it was just a practice project, something to use for learning and to put on my resume.  Then I was adding things that I wanted for my own uses.  Then it started getting popular, and now most of what I work on has been at the request of other people.

Remotely is now a second job that pays me in a month less than what I make in *30 minutes* at my actual job.  Let that sink in.

How long would you keep that up before wanting something in return for all your effort?  How many times would you tell your 6-year-old, "I know daddy said he has the day off, but this is different."  And for what?  So people can have a free remote access tool?  Because they don't want to pay enough that someone could actually make a living?

It's not just the coding itself.  Even though that alone would be enough to not want to do this anymore.  It's also the constant barrage of emails.  It's the constant requests for help, most of which have nothing to do with Remotely itself and more about not knowing how to set up a web server in general.  Then there's the occasional lashing out from people who want more support for their free software.  The sense of entitlement is insane.

Then there are the frequent, "I'll sponsor you if you do XYZ."  Until you do XYZ, then they want ABC too.  They'll keep dangling that carrot in front you forever if you let them.

I started this project for me,  But I've been done for a long time.  I've accomplished what I set out to.  I'm allowed to call it done and archive the project.  I'm allowed to use my free time for myself and my family.  Just because people are using it doesn't mean I'm obligated to do anything.  Yet everyone keeps treating me like I'm under obligation to ensure the project lives on indefinitely and continues to benefit everyone else.

And there's absolutely nothing wrong with wanting to keep the project *mine*, in a copyright and ownership sense.  It's my project.  I made it.  I hold the copyright.  Yet people seem to confuse open-source with ownership.

An open-source license permits people to use it specific ways.  It doesn't mean I'm *giving* it to people.  Nobody else owns it.  And I repeat, there's nothing wrong with wanting to retain ownership of my project, even if I archive it.  Authors don't give away the copyright to their books when they've completed the series.

Anyway, I'm done ranting.

**Comment by stevesobol** [comment]
Ok. Now I'm a little pissed off.

I'm specifically NOT REQUESTING ANYTHING FROM YOU.

I've BEEN saying I WANT TO HELP BY CONTRIBUTING WORK, SINCE I CAN'T HELP BY CONTRIBUTING MONEY RIGHT NOW.

I've BEEN saying that. I've said it recently. And I'm not a Mac expert, but for God's sake, Jared, I have a Mac with all of the dev tools installed on it because it's where I work on my mobile apps. I can help with a Mac port, and there's an open issue requesting help with that exact thing.

But that's the thing. This is your baby. I get it - I'm the same way. But to complain about people asking you for tons of work that you're not going to get paid to do, and then, when someone offers to take some of that work off your plate without requiring any compensation for it, telling them you're not interested... I mean, come ON, man, you and I have HAD that conversation in the recent past! 

This is a great project. I want to shoot some money your way, but since I can't, I at least wanted to contribute code. I'm going to heavily customize Remotely for my own environment, so I'm in Visual studio slogging through the code *anyhow* - so why not give back? 

Do you understand that I am trying to recognize the huge amount of work you've undertaken, and trying to help further the project without putting more of a strain on your workload? BTW, I have kids, so I understand where you're coming from.

And yet here you are, launching into a big rant about A BUNCH OF THINGS I'M NOT DOING.

I asked for help once, yes. The problem was caused by a screwup in my config. I didn't realize that until later, and I apologize. But I'm trying to help you here, and I wish you'd realize that.

If you're not going to, well... I just forked the project and will do what I was going to do anyhow.

But for God's sake, man. Don't come at ME because you're frustrated about things OTHER people have done. I respect and appreciate the insane amount of time you have put into this project. It's really, REALLY well done. And if you want to archive the project, who am I to argue or complain? All I was saying was "make up your mind." That's literally the *whole* point of my last comment. I don't think I deserve what you just threw at me.

**Comment by stevesobol** [comment]
OBTW, please email me. steve@LobosStudios.com. Please tell me how you'd like to receive money for your efforts. I literally can only spare a few bucks this week, but I feel it's appropriate to give you something, even if it's only a small amount.

**Comment by lucent-sea** [comment]
Dude, I never accused you of anything.  I'm not "coming at you."  I'm simply stating facts about what my experience has been like with other people while supporting this project.

This thread has turned into an prime example of the kind of stress I'm trying to avoid, though.

There are reasons that I've been hesitant to accept code contributions.  I've been flip-flopping because I'm *unsure* of my plans for Remotely.  Or if I'll ever be able to monetize it.  The fact is that code contributions at this point don't really help me.  They might help other people, yes.  But it also means I no longer own 100% of the codebase.  It adds legal complexity if I ever have the opportunity to explicitly sell services or sell the codebase.

Any significant code contributions also require time to review.  If it isn't well-architected and/or well-tested, it would be easier for me to break because I'm not as familiar with it as I would be if I had written it.

In the case of something as major as a Mac agent, that would present real challenges for me.  I'd need to set up a Mac build server for my CI/CD process and orchestrate it with the existing Windows server to produce the final package.  That's a huge undertaking itself.  And my understanding is that Mac is pretty strict about code signing and such, so there might be additional things required for the build process.  GitHub Actions would need to be updated with the same.

Then there's the support aspect.  Things are bound to not work or break.  I have no way of debugging or testing the Mac agent because I don't own a Mac.  So I'd need to buy a Mac with a multi-monitor setup.  I'd have to test it regularly, which is more work.

Hopefully this explains why it's not as simple as, "Why aren't you accepting my help?"  It's a lot to consider, especially when I haven't decided on an end goal.

As for donating, please consider giving to a charity here: https://www.givewell.org/charities/top-charities  It would have a far greater impact on their lives than mine.

**Comment by stevesobol** [comment]
Ok, I understand. I honestly thought you were attacking me for making that first comment.

Here's why I want to work on Remotely, for myself if for no one else: Because so many Americans are being stupid about COVID, we're not going to get back to life as usual for a while. I actually planned on stopping all of my support work for everyone except a couple small businesses I've supported for years, and focusing 100% on web and mobile development.

Then I realized that there's a market for no-touch tech support.

THEN I realized that my competition isn't marketing themselves as fully-remote, when they should be making a HUGE push to position themselves that way. Even Best Buy is focused primarily on curbside pickup and getting merchandise sold and out the door. Not one peep out of them about Geek Squad. (not to mention, with a quarter-century of experience, I can do better than Geek Squad can, anyhow)

So right now, I'm trying to figure out how and where to market my services. I have a couple other people I'm bringing on.

I use ConnectWise Control for remote support. It works well. The problem is that the branding options suck. They're basically nonexistent. Since I have the source for Remotely, I can customize it to my heart's content, and that's what I am doing. Also, I can remotely control computers from anywhere, because all I need is a web browser. With ConnectWise, you have to have their client installed and running.

There are some shortcomings, like "hit ctrl-escape with the remote-control window in focus, and the remote computer AND the local computer both process it." I'll deal with those. That one, in particular, seems like it's caused by Remotely running in the browser, as opposed to a separate app. I'd like to fix it, but I haven't looked into how to fix it yet.

But I'm in a different position. You have a full-time job. I'm 100% freelance and as a result, my schedule is much more flexible than that of a 9-5 employee. Things are insane right now, but I expect that in February, I'll be able to continue working on Remotely.

Regarding losing ownership? Doesn't have to be that way. I have signed CLAs with a couple different OSS orgs. Apache's one. I believe Eclipse is the other. Those agreements dictate who owns the copyrights.

**Comment by lucent-sea** [comment]
I'm sorry for allowing my frustration to come through in my writing.  It's not directed at you.  This project is just taking a lot out of me, at a time when I don't have much extra energy to spend.

I'll think about this some more and get back to you.  But in the meantime, I apologize if I've offended you or made you feel attacked.

**Comment by stevesobol** [comment]
Eh. I accept the apology, but you didn't really need to apologize. I'm this cranky in real life, too. Also: get off my lawn.

But yes, please think about it. I'm willing to help as soon as I have a bit of bandwidth.

**Comment by swilkey** [comment]
Hi Jared and Steve,

I'm chiming in here because I have a suggestion.  Maybe my suggestion isn't workable but I want to raise it in case it offers an acceptable way forward.

Let me say that I also understand the pressures of working on a voluntary project like this and the need to balance family life (I have a 7 year old myself) and although I can't contribute cash (being a volunteer myself and living off other's generosity while I work for a donor funded organisation) I monitor all these requests about remotely and offer help when I can so that I can relieve some of the pressure on Jared when I know the answers that are being asked for.

I'm wondering if it would be possible for Jared to continue to own and control the codebase for this without necessarily having to own the codebase for a mac client?  I think of other open source projects where third parties contribute tools to integrate with the core product.  Here, remotely server could be the core, with remotely windows and linux clients being the official clients but Steve could contribute the Mac client as a third party client that is written to communicate in the same standard way that the windows and linux clients communicate with the server.  That way anything that could be supported directly by being compatible with the existing communications flows could be enabled, and if Steve saw a need to request any additional functionality on the server to support something on the mac client then it would be up to Jared to decide if he was willing to incorporate that in the core codebase (even if Steve contributed the actual code change).  If Jared decided not to incorporate the additional code then Steve could always fork the whole project to provide the additional functionality he was after, but that would again prevent Jared from feeling the need to take on support for something extra.  

In my overly simplistic way of thinking about it, all that would be needed for this to happen would be that the communications between the server and client be standardised (which they probably are already) and as long as anything Jared does in his codebase still enables that same standardised communication, it should then work with the mac client codebase too.

Like I said, if this isn't workable just ignore it, but if this helps, great!
Regards,
Stephen
