### ISSUE TITLE
RE:Session ID

### ISSUE THREAD

**Issue by vaibhavkulkarni1** [lucent-sea/Remotely#199]
Can we control our own session id permanently as it it changing every time.

**Comment by iFieldSmart-Tech** [comment]
We are trying to use remotely from a custom frontend where each user can see only a limited set of remote devices. We are storing the device id in a database and based on that, we are calling the RemoteControl api. But the issue that sometimes it connects, while sometimes it leads to the screen that asks for the session id. We understood that it can be obtained by running the Remotely_Agent executable on the remote machine, but is there any way to do it programmatically? Is there an API that gets the current session id for a remote device?

**Comment by lucent-sea** [comment]
@vaibhavkulkarni1  The session ID is randomly generated by SignalR when the application connects to the server.  The Remotely Agent service launches a new instance of Remotely Desktop app each time a remote control session is requested, which then generates a random session ID.  The Remotely Desktop needs to be launched as a separate process in the active user's Windows Session because services (running in session 0) don't have access to the desktop (for screen capture and input simulation).

It's not permanent by design.  I might change this to use the device ID instead, but I'll have to think about it.

@iFieldSmart-Tech Same as above.  When you call the RemoteControl API, there isn't currently a remote control Session ID.  Only a session ID for the Remotely Agent service.  The service then launches the Remotely Desktop app in the active user session.  The Remotely Desktop app automatically closes after 30 seconds if no one connects.

When using the API doesn't work, do you see the below message?  If so, it might mean that the remote control session wasn't started fast enough, and the Remotely Desktop app already closed.

But it's impossible to say without logs and timestamps.

![image](https://user-images.githubusercontent.com/20995508/103178675-b4e25680-4839-11eb-951d-33ce149a8995.png)

**Comment by iFieldSmart-Tech** [comment]
@lucent-sea - Thanks for your prompt response.

"The Remotely Agent service launches a new instance of Remotely Desktop app each time a remote control session is requested, which then generates a random session ID."

Is it possible to store this session ID somewhere when it is generated or maybe a way to get the current session ID when the remote control API is called? If it were not generated randomly, we would have tried generating it on the server side, but I guess that is not an option as it is random. That leaves just one option, to fetch the current session ID. Also, is it possible to extended the timeout from 3 minutes to like 5 or 10 minutes?

**Comment by iFieldSmart-Tech** [comment]
@lucent-sea 

Even if the connection is established, it only lasts for 30 seconds to 1 minutes and then shows the above window saying session id not found. Can you please help us out here

**Comment by lucent-sea** [comment]
> or maybe a way to get the current session ID when the remote control API is called?
That's what the remote control API does.  It calls the Remotely_Agent service and tells it to launch the desktop app in the user's session.  Once it's ready to capture the screen, the API returns the session ID.

It would be possible to extend the timeout, but I don't want to.  The intent is to limit the time it's running in the user's session.  If I wanted to save a session ID and use it 10 minutes later, I'd instead just call the API in 10 minutes when I'm ready to start the session.

If you're trying to start unattended remote control sessions without having the Remotely_Agent service installed, it's not possible.  The desktop app needs to be launched from a service running as SYSTEM in session 0 in order to obtain access to the UAC and WinLogon screens.

As for the session ending, it's probably due to a improper proxy configuration or unstable internet connection.  I use Remotely every day and don't have an issue.  I'm also not getting reports from other people.  But I can't account for all the variables of your remote client's system, their network connection, your server, your proxy configuration, and all the infrastructure in between.
