### ISSUE TITLE
Database questions

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#208]
Not expert on database, requesting for your kind assistance.

Cant change the database to postgresql.

My question is if i use the remotely in production what is the disadvantage and advantage if i use the default settings of database sqlite 

if there is limitations of number of users or to the system. number of device read,users,

Or it's ok to use the sqlite .

thank you

**Comment by chasekidder** [comment]
You can take a look at the differences between different DBMS' to determine what fits your use case. This [Digital Ocean](https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems) article explains some common use cases where it makes sense to use one over another. When it comes right down to it, the only big factor is whether you already have a database server running that you can use or if you need to spin up a new one. 

I have a PostgresSQL 11 server that I need for a specific application so I use that for every application that supports it simply because I don't want to have to admin another one. Most of my apps are in Dockers so I try to keep away from sqlite except for testing. In the end, look at your use case and decide for yourself what's most important.

**Comment by lucent-sea** [comment]
The above article sums it up pretty well.  I think in the vast majority of cases, SQLite will work fine from a technical and performance aspect.

The majority of database writes are happening when the devices check in with their latest info (every 5 minutes).  I honestly don't know the number of devices you'd need to add before you start seeing performance issues.  I tried stress-testing once, but I ran out of RAM from all the websocket connections before the database ever stuttered.  It was in the thousands.

The only other consideration is if you want to make manual changes in your database (e.g. via DB Browser for SQLite program).  If you start writing changes, it will lock the database, and the server won't be able to write to it.  So if you're going to do that, it's best to wait until you can stop the server for maintenance.

Hope that helps.
