### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by BORIKKEN21** [lucent-sea/Remotely#239]
When I run sudo sh Ubuntu_Server_Install.sh

"Thanks for trying Remotely!

Ubuntu_Server_Install.sh: 5: Ubuntu_Server_Install.sh: Syntax error: "(" unexpected
"
I've cat the script but the "(" is there.

Anyone had the same problem while upgrading?

Currently at Version: 2020.12.19.2323

**Comment by lucent-sea** [comment]
No issues here.

https://user-images.githubusercontent.com/20995508/107843268-9fd86d00-6d7e-11eb-8344-1fc2b55e38a5.mp4

**Comment by sinichi19** [comment]
upgraded my remotely without problem.

you can also downloaded direct the latest system. and overights your source or root folder.
https://github.com/lucent-sea/Remotely/releases/download/v2021.01.22.0533/Remotely_Server_Linux-x64.zip

**Comment by RecursiveProgrammer** [comment]
I think I can help with this:

Since your version is: 2020.12.19.2323

Unless the version number just was not updated, then you have not received the update which fixes the issue ( https://github.com/lucent-sea/Remotely/blob/master/Server/wwwroot/Downloads/Install-Ubuntu-x64.sh (that update was on January 29th) ) . I believe the two easiest methods would be to do what sinichi19 suggested (downloading the zip file) or, I believe, you can download the shell script, directly to the server, in the appropriate directory (usually /var/www/Remotely/wwwroot/Downloads/ (or where ever you may have installed it to)).

Cheers!

**Comment by lucent-sea** [comment]
Closing due to no response.
