### ISSUE TITLE
Total storage only takes into account the main disk

### ISSUE THREAD

**Issue by rtm516** [lucent-sea/Remotely#243]
The total storage displayed in the GUI only shows the primary drive on the machine (only checked in windows) and therefore displays the used percentage wrong.
![image](https://user-images.githubusercontent.com/5401186/108002177-ab2dd180-6fe6-11eb-80de-5dd5e3a0e68e.png)

**Comment by lucent-sea** [comment]
This was an intentional design.  In almost every scenario, I'm only concerned with the free space on the system drive, and I wouldn't want that figure to get thrown off by other drives on the system.

Information for all drives is stored in an array in `Device.Drives`, but I'm not doing anything with them currently.  I had intended to display them in some way, but moved on to other things.  You can modify `DataGrid.RenderDeviceRows` to display the information differently.
