### ISSUE TITLE
Losing input control on both remote and local

### ISSUE THREAD

**Issue by MrAlfabet** [lucent-sea/Remotely#248]
I just installed the latest version and I'm having some issues with remote control. After starting a session I will lose the ability to click, and sometimes also the ability to type. In some occasions, the inability to click on certain things persists on the client pc after closing the session. Those certain areas include the windows task bar, explorer windows, the task manager and chrome tabs. This leaves the client to hard-reset his pc, or do some 'voodoo' like win+r > shutdown command.

Has anyone experienced these kinds of issues?

**Comment by lucent-sea** [comment]
I haven't encountered this myself.  Are there any errors in the client logs when this happens?

Is there anything toggled when this happens that's different from the default settings (e.g. Stream Mode, Block Input, Audio, etc.)?

**Comment by dsinfinite** [comment]
I have been having this issue randomly. It is due to the Control or Alt key getting stuck being held in a down state. I mainly see it start when alt-tabbing to a different window when connected to a remote session. I then need to tap control and alt a couple of times to fix.

It has only happened 5 or so times over hundreds of sessions when I disconnect that the client can't work - having them hit control and alt a couple of times fixes the issue as well.

**Comment by MrAlfabet** [comment]
I can tell it happens more often if I try to use the middle mouse button (press scroll wheel) to close tabs in chrome. I'll do a thorough investigation later today.

**Comment by MrAlfabet** [comment]
I can consistently reproduce this under the following conditions:

windows 10 pc as host with chrome browser
windows 10 pc as target

try to close a chrome tab on the target pc with a press of the middle mouse button, and no longer are 90% of mouse clicks registered. Weirdly enough I do seem able to resize windows but I cannot move them around or put the cursor in an address bar (both google chrome address bar and windows explorer address bar)

Please advise on how to properly investigate this.

**Comment by MrAlfabet** [comment]
I have a new issue now: the client instance crashes upon login, which gives me the message 'The host has disconnected.'

**Comment by lucent-sea** [comment]
I'm able to reproduce issues with the middle mouse button.  There doesn't appear to be anything I can do to fix it.  I'm using the same [Windows API](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput) as I'm using for all the other mouse input, so I'm not sure why middle mouse button would have issues.  All I can do is disable it (e.g. not send it through).  In the meantime, you can send a Ctrl + Alt + Del to unstick it.

I'm not encountering any client crashes, so I can't help there.  If you post logs, someone might be able to help.

**Comment by MrAlfabet** [comment]
Where can I find the logs if I'm using the click-and-run exe?

**Comment by lucent-sea** [comment]
https://github.com/lucent-sea/Remotely#logging

> %temp%\Remotely_Logs.log

**Comment by ggg1psyyy** [comment]
Hi, I'm just evaluating remotely and had the same issue. The problem is that the MiddleMouseButton-Up event would never reach the client, so it would always stay in the Down state. 
I traced it to the `viewer.addEventListener("mouseup", function (e: MouseEvent)` in "Server/wwwroot/src/RemoteControl/InputEventHandlers.ts".
There the middle mouse button is explicitly removed from the handling. I deleted the "offending" lines:
`if (e.button != 0 && e.button != 2) {
                return;
            }` and now it's working as expected.
I don't know if there are any unexpected consequences, but as it's allowed in mousedown, I can only think it's an oversight and there shouldn't be any (more) negative side effects.

**Comment by lucent-sea** [comment]
@ggg1psyyy Nice catch!  Thank you for looking into this.  It was indeed an oversight when I initially added middle mouse click.

I'll update this soon.  I'm currently working on a major rewrite, using Blazor instead of Razor Pages + JavaScript.  The project has gotten too big to keep going like this without a front-end framework.

**Comment by lucent-sea** [comment]
Test has been fixed.
