### ISSUE TITLE
Desktop.Win\Engine\Launcher.exe not found

### ISSUE THREAD

**Issue by engelant** [lucent-sea/Remotely#265]
I tried to build the project as described per "Build Instructions (Windows 10)" and I stumble upon the error during execution of the command:

`powershell -f [path]\Publish.ps1 -outdir C:\inetpub\remotely -rid linux-x64 -hostname https://mysite.mydomain.com`

Unfortunatly the System locale is DE, sorry...
```Freigegebene Kompilierung mit dem Compiler aus dem Verzeichnis wird verwendet: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4046,5): error MSB3964: Die erforderliche Datei "C:\Users\Administrator\remotely\Desktop.Win\Engine\Launcher.exe"
wurde nicht gefunden. [C:\Users\Administrator\remotely\Desktop.Win\Desktop.Win.csproj]`
```

This leads to the Server displaying an Error message, if I navigate to the /Agents URL (Downloads Tab).
```
Error.
An error occurred while processing your request.

Request ID: 00-1a2d50432d10f94d9487c95dce6a42d7-c874b03ca0be1147-00
Development Mode

Swapping to Development environment will display more detailed information about the error that occurred.

Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the ASPNETCORE_ENVIRONMENT environment variable to Development, and restarting the application. 
```

**Comment by lucent-sea** [comment]
Hello!

It sounds like you may have the wrong .NET SDK installed, or maybe the installation is corrupt.  

The project now requires the .NET 5 SDK (not .NET Core).  The readme is outdated, but I'll be updating it with the release of the next version. 

Did you happen to install the .NET Core 3.1 SDK?  If so, you can install the .NET 5 SDK and try the build again.

Otherwise, I'd recommend using the `Build` workflow in GitHub Actions.  The resulting ZIP file will be the same as what the `Publish.ps1` script produces.

![image](https://user-images.githubusercontent.com/20995508/114055772-e5c52500-9845-11eb-8175-d5e76ebc7eb9.png)

**Comment by engelant** [comment]
I gave it a try using github actions, and it worked. I'll have to bring up the VM I used to buidl again and see if installing the .NET 5 SDK will resolve the issue. I actually just installed the Stuff from the VSCode Installer, but I remember selecting core and something with NET 5, but that might just have been the runtime.
