### ISSUE TITLE
I can't make Windows Build

### ISSUE THREAD

**Issue by Peace569** [lucent-sea/Remotely#302]
I have built the "Desktop.WIn" project (in Remotely solution).
I made the release version, so it is working well on my PC.
But it is not working on another pc. It requires .net 5.0 package install.
1. I downloaded the .exe file from the "app.remotely.one" site. this exe file is working well on every side.
    Can't I build like this exe file? How can I do?
2. If I can't build like so, how do I have to do for every PC?

I am waiting for your help.
Regards

**Comment by nickm324** [comment]
Did you find a resolution to this, I am getting the same issue and I have made sure all the .Net 5.0 SDK and 4.8 and Core are installed on my machine but I cannot build due to .NET50 errors.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	Shared	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1177

**Comment by Peace569** [comment]
@nickm324 , you can install .net 5.0 package, then you can solve everything.
What I am going to know is that I build exe file for executing it without package install on any PC.
And I am also getting the errors on some WIndow 10 PCs when I am excecuting exe file even thought I installed .net 5.0 package.

**Comment by nickm324** [comment]
> @nickm324 , you can install .net 5.0 package, then you can solve everything.
> What I am going to know is how can I build exe file for executing it without package install on any PC.
> And I am also getting the errors on some WIndow 10 PCs when I am excecuting exe file even thought I installed .net 5.0 package.

Like I said above I already installed the 5.0 SDK with .net core and I am still getting these errors.

**Comment by lucent-sea** [comment]
Please see https://github.com/lucent-sea/Remotely/issues/310
