### ISSUE TITLE
reference assemblies for .NETFramework,Version=v5.0 were not found

### ISSUE THREAD

**Issue by nickm324** [lucent-sea/Remotely#310]
**Describe the bug**
Cannot build from source.

**To Reproduce**
1. Download current and previous versions of source.
2. extract to folder.
3. Open solution in VS 2019.
4. Attempt to build.
5. Fails with several errors.

**Remotely Version**
Remotely-2021.03.25.2059

**Expected Behavior**
Expected to build project.

**Screenshots**
![image](https://user-images.githubusercontent.com/6774571/115873559-b2b78f80-a408-11eb-8251-6f76c2beee11.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser  N/A
 - Version Remotely-2021.03.25.2059

**Additional Context**
Also many missing assembly references.
![image](https://user-images.githubusercontent.com/6774571/115873775-f5796780-a408-11eb-8878-be0ef7fdc700.png)

**Comment by lucent-sea** [comment]
Packages are installed through NuGet Package Manager.  Visual Studio will download and install these on the first solution build.  Since that's not happening, you're probably missing components in the Visual Studio installation.

I've updated the install requirements in the readme.  Make sure you have all of those checked.

If you're still having problems building, I'd recommend asking in the Discussions tab or on Reddit.  More people are likely to answer there.

Thanks!  :)
