### ISSUE TITLE
docker-compose.yml does not preserve config over restarts

### ISSUE THREAD

**Issue by heurekus** [lucent-sea/Remotely#329]
Your Docker container and the docker-compose.yml description on Docker hub made for a very quick and smooth server install. Thanks very much! 

I noticed however, that the configuration did not survive a docker-compose down / docker-compose up -d cycle. All config information was lost. I had to create an admin user again and all settings made were not present anymore. I guess this is not intentional? 

Is the volume mapping correct? I took the yml description on Docker hub as it was and made no changes. No reverse proxy or anything else added either.

**Comment by lucent-sea** [comment]
Oh, I'm sorry. I should have removed the compose file for now. As I was working on the Docker image, I realized that I would need to change how the Server Config page saves and loads in order to get it saving appsettings to the volume.

So the volume isn't being used yet. You need to back up and restore the two files manually as shown on the Docker repo.

I can revisit this after the Mac agent. I'm not sure yet the extent of changes that will be needed in the server code.

**Comment by lucent-sea** [comment]
I got this working now.  Both the `appsettings.json` and `Remotely.db` will be saved in the volume by default and will persist through container recreation.

**Comment by heurekus** [comment]
Yes, works now, thank you!
