### ISSUE TITLE
Size of Instant Client

### ISSUE THREAD

**Issue by hubermarkus** [lucent-sea/Remotely#345]
The size of the Windows Instant Client has extremly grown to older versions.
Is this because the .net core framework is packed into the .Exe?

Would it be possible to run on Plain .net Framework 4.7 or 4.8 without major mods?
It would be great to have an Instant.exe with around 20-50 MB.

Markus

**Comment by lucent-sea** [comment]
Yeah, the size is due to being self-contained.  It has the runtime embedded in it, so users don't have to install that first.

Going back to .NET Framework 4.8 isn't going to happen, unfortunately.  I've already invested too much in going forward with .NET 5.

The EXE size should decrease later this year when .NET 6 releases.  Microsoft has stated that assembly trimming should be finished by then.  It reduces the size of self-contained executables by stripping unused assemblies from them.  I tried using the current preview version in .NET 5, but it was buggy.

Alternatively, you can use the ClickOnce installer (screenshot below).   It will install the runtime on the first install.  Afterward, it will auto-update whenever a new version of Remotely shows up on your server, but it only has to download changed files.  It ends up being around 15-20MB to update.

![image](https://user-images.githubusercontent.com/20995508/117297178-c4e2f600-ae2a-11eb-80cd-da6f465d3679.png)
