### ISSUE TITLE
Hi CPU usage on IIS when the user search a server by name

### ISSUE THREAD

**Issue by telluria-raphael-advincula** [lucent-sea/Remotely#355]
Describe the bug
Hi CPU usage on IIS when the user search a server by name on remotely interface

1. Log on remotely
2. Type a computer name on the search box
3. See the CPU usage on IIS increase considerably

**Remotely Version**
Server v2021.05.12.0503 
Agent (we tested with several versions)

**Expected Behavior**
CPU consumption remains stable as it is in versions prior to v2021.04.29.0623

**Desktop (please complete the following information):**
 - OS: Windows Server 2012
 - Browser  chrome 
 - Version 90.0.4430.93 (Official Build) (x86_64)

**Additional Context**

**Comment by lucent-sea** [comment]
It probably uses more CPU now due to the locks I put around the device collections.  They were necessary to prevent exceptions caused by multiple threads accessing the collections at the same time.

I changed the search box so it only performs the search after pressing enter or tabbing/clicking out (i.e. onchange event) instead of updating with every keystroke.  This should reduce the CPU usage.

**Comment by telluria-raphael-advincula** [comment]
Thank you! When will this fix be available?

**Comment by lucent-sea** [comment]
It's on master now if you're able to build from that.  Otherwise, I'll get a release out this weekend after I've tested on my staging server for a bit.

**Comment by telluria-raphael-advincula** [comment]
Just one more question, before this new interface there was no problem. Was there a change in that code?

**Comment by lucent-sea** [comment]
Yeah, it was a big change.

I completely rewrote the server using a new framework called Blazor.  There are two versions of it: Blazor WASM that runs .NET completely in the browser, and Blazor Server that runs everything on the server and streams small HTML/CSS diffs to the browser.  I'm using Blazor Server.

There were a couple reasons for choosing Blazor Server over a client-side framework like Blazor WASM or React.  Some consider Blazor Server "more secure" because it runs everything on the server and doesn't expose any public endpoints for retrieving data from the server.  I'd argue that client-side frameworks are just as secure if done properly, but there's less risk of accidentally leaking something with Blazor Server.  The browser only ever receives what's visually displayed.

The other considerations were productivity and maintainability.  For me, Blazor Server is the fastest framework for development.  It's also the most easy to maintain, in my opinion.  It just works.  With React, every time I have to update one of the thousands of JavaScript libraries it depends on, something breaks.

Before Blazor, I was doing all the client-side functionality manually with vanilla TypeScript.  I tried to keep it organized, but it just becomes unmaintainable after a while.  Too many direct calls to the DOM for updates, etc.  Adding features or changing behaviors was becoming too difficult.

The other thing that would have been difficult with client-side frameworks is that users would need to create and configure certificates that are used to sign the authentication tokens.  This is in additional to normal SSL/TLS certificates.  The certificate is required because client-side frameworks don't maintain persistent sessions like server-side frameworks do.  So, to keep you logged in, it has to encrypt a token and send it to the browser after successful login.

So it would have been extra work for users.  And they'd have to remember to renew the certificates (or automate it).

The trade-off with Blazor Server is that, since everything runs on the server, it will use more resources.  And if there's too much latency between you and the server, you'll notice some lag when interacting with things.  My prod server has 1k devices on it, though, it's only using 25% of its 2.5GB RAM.  And I haven't seen any sustained CPU utilization.

I intentionally put my staging server about 2,000 miles from me, and I barely notice latency.

Anyhow, probably more than you wanted to know.  :)

**Comment by telluria-raphael-advincula** [comment]
Thank you very much for the explanations!

**Comment by lucent-sea** [comment]
Hmm.  Apparently Brew can't run as sudo.  I'll have to take another stab at this later.  Maybe using MacPorts.

**Comment by lucent-sea** [comment]
I changed the input to refresh `onchange` instead of `oninput`, which reduces the amount of work being done on the server.
