### ISSUE TITLE
Issue with MSSQL Server

### ISSUE THREAD

**Issue by R4PH1** [lucent-sea/Remotely#68]
Hi,

it seems there is an issue installing the tables on an mssql server (2017):

from windows eventlog:

Category: Microsoft.EntityFrameworkCore.Database.Command
EventId: 20102

Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [AspNetRoles] (
    [Id] TEXT NOT NULL,
    [Name] TEXT(256) NULL,
    [NormalizedName] TEXT(256) NULL,
    [ConcurrencyStamp] TEXT NULL,
    CONSTRAINT [PK_AspNetRoles] PRIMARY KEY ([Id])
);

executed in sql management studio manually:

Msg 2716, Level 16, State 1, Line 1
Column, parameter, or variable #2: Cannot specify a column width on data type text.

In my opinion it should use varchar(256) instead.

Only dbo.__EFMigrationsHistory was created in the database.

Would love to try out the software with mssql.

**Comment by Jay-Rad** [comment]
Hi!  Thanks for the report.

I had actually forgotten about this.  The problem is that these migration files are automatically generated with the Sqlite provider, so they aren't going to work for MS SQL.  To use another DB provider, one would need to delete the migration files, change the DB provider, and re-create the migrations.

There's a way to generate migrations for multiple providers, which is explained here:  https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli

I'm not sure when I'll get around to doing this, though.

**Comment by lucent-sea** [comment]
Moved to https://remotely.featureupvote.com/ for voting.
