### ISSUE TITLE
Unattended access

### ISSUE THREAD

**Issue by swilkey** [lucent-sea/Remotely#80]
Hi Jared,

So I've discovered that it is only possible for me to use the unattended (service) version of remotely.  This is because our internet connections are apparently not stable enough in this country for the normal instant client and as a result of that, if there is any glitch in the connection, the instant client just closes, assuming that the session was complete, and the only way to get back connected again is for the user to run the client again and give a new number to the remote person to enter.  This would obviously be impractical for an average help session.

The unattended access is able to sustain a session well enough.  However, I understand that there is an option to use webrtc for the session so that it can try to establish a peer-to-peer connection.  I have my remotely server in AWS and I was trying to remote control the computer sitting next to me on my desk - is there any way to know if it was successful in doing this by webrtc or if the entire session was going via the aws server?  I cannot see this in the logging on the server so I do not know.  I do know that my appsettings.json has webrtc set to true by default.  I just don't know if it is succeeding and I'm getting the best performance that I can.

The other issue I have is that because I'm forced to use the service version of remotely rather than the instant client, there doesn't appear to be any warning to the user that you are taking over their computer as there would be on the instant client.  I am wondering if there would be a way that we could optionally set a setting on a client so that the service functions in the same way as the instant client by popping up a message saying that "so and so would like to remote control your computer"?  If there was a way to do this, I'd love to set it as the default setting on all my installations and to just disable that on a few where true unattended access is required.  I'm not sure if this is something you've thought about before.

Regards,
Stephen

**Comment by swilkey** [comment]
Regarding the unmessaged, unattended access: I took a look at the code, I'm not a C programmer so I'm just guessing, but it looks to me like it is simply a case of flipping a switch in the routine that calls the screen casting from -Unattended to -Normal in the agent.  If it really were that simple, then it would even satisfy my requirement to have one version of the agent that was setup for -Unattended and one for -Normal, and I'd just install the "normal" one everywhere I need it with the "unattended" one being kept for truly unattended use.  Am I close?

**Comment by Jay-Rad** [comment]
Hi, Stephen.

I've added an indicator at the bottom of the remote control menu that shows if the connection is relayed or P2P.  It'll be in the next release.  Until then, you can check the browser's console.  It'll say "Data channel opened." if the WebRTC connection succeeded.

There are technical challenges with adding any UI elements to the unattended service, and I'm not ready to tackle them yet.  Even so, I'm not sure I want to add an attended access option to the unattended service.

And unfortunately, it wouldn't be as easy as flipping a switch.  The server handles attended and unattended sessions differently.

However, I will look into reconnecting sessions through network disruptions.  If there's a way to implement it easily, I'll put it in the next release.  But if it will require a lot restructuring, it will probably have to wait for a while.

Between work and family, I don't have a lot of time to work on this, and there are a handful of other things I want to do first.

I'll update here if there's progress.

Thanks.

**Comment by swilkey** [comment]
Thanks very much Jared. Wonderful regarding the Webrtc connections.

Regarding the attended access request - for now I might approach this simply by switching the service to manual start up instead of auto, and giving users a shortcut to turn it on and off as required.

**Comment by Jay-Rad** [comment]
Hey, Stephen.

I sent you an email with something to try out.  Just letting you know here in case my email got lost in the junk folder.  :)

**Comment by swilkey** [comment]
Thanks Jared, got it, but it is the weekend here so I probably won't get 
to test it till Saturday.
Regards,
Stephen

------ Original Message ------

**Comment by swilkey** [comment]
Just checking that you did get my reply to that email?

**Comment by Jay-Rad** [comment]
Hi, Stephen.

I did get your email.  I've been getting a lot more emails lately regarding Remotely (like ten times as many), and I haven't had time to respond to them all yet.  There's a lot going on in my personal life now too, so development on Remotely will be slowing down for a while.

To answer your questions, I don't know all the factors that can contribute to WebRTC being unable to establish a connection.  The unattended install will add a firewall exception for the screencaster EXE.  The instant support client should prompt to add the exception on first use.  If it doesn't, you can try adding a firewall rule manually.  Beyond that, I don't know what else you can do to.

The instant support client won't have access to UAC unless you relaunch it with "Elevate to Service".

When the connection breaks due to network interruption, the "viewer" does get removed, but it just wasn't bubbling up to the visual level.  I'll fix that.

After looking into it some, there is no easy way to "refresh" a connection that's broken due to unstable internet.  The authentication flow that I made wasn't built for it.  I'll look into it more in the future when I have time.  But for right now, I'm afraid I don't have time.

**Comment by swilkey** [comment]
Thanks Jared, understood regarding workload.  I completely understand.  It
isn't as if this is a paid solution so things take time.

Regards
Stephen

**Comment by lucent-sea** [comment]
This has been moved to https://remotely.featureupvote.com/
